### ISSUE TITLE
Error opening in ue 5.4

### ISSUE THREAD

**Issue by daromero2** [vahabahmadvand/ActionRPG_UE53#2]
Error opening in ue 5.4
After opening in ue this notification appear
![image](https://github.com/user-attachments/assets/34774795-f657-422d-b702-e8ef7e9838d3)
if select "Yes" a compile error appear and if select "No" and open it without rebuild another error appear
![image](https://github.com/user-attachments/assets/fc95b66c-f6cd-4a3b-9e0d-241a18d68c68)

**Comment by vahabahmadvand** [comment]
Please ensure that you have generated Visual Studio project files and compile it using VS2022.

Everything has been tested, and everything is functioning properly.
